import{a as u,S as p,i as a}from"./assets/vendor-CBqwhNxR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const m="https://pixabay.com/api/",f="49829256-73c1564e94f64863eabbb2525";function d(o){const r={key:f,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return u.get(m,{params:r}).then(e=>e.data).catch(e=>{throw console.log(e),e})}const g=new p(".gallery a"),l=document.querySelector(".gallery");function y(){l.innerHTML=""}function h(o){const r=o.map(e=>`<li class="g-item">
        <a href="${e.largeImageURL}"><img class="g-img" src="${e.webformatURL}" alt="${e.tags}"></a>
        <ul class="g-list">
        <li class="g-list-item"><span class="text">Likes</span> <span class="num">${e.likes}</span></li>
        <li class="g-list-item"><span class="text">Views</span> <span class="num">${e.views}</span></li>
        <li class="g-list-item"><span class="text">Comments</span> <span class="num">${e.comments}</span></li>
        <li class="g-list-item"><span class="text">Downloads</span> <span class="num">${e.downloads}</span></li>
        </ul>
        </li>`).join("");l.insertAdjacentHTML("beforeend",r),g.refresh()}const w=document.querySelector(".form"),L=document.querySelector("input"),c=document.querySelector(".loader");function b(){c.style.display="flex"}function S(){c.style.display="none"}w.addEventListener("submit",o=>{o.preventDefault(),b();const r=L.value.trim();if(!r){a.warning({message:"Please, enter a search query",color:"yellow",position:"topRight"});return}d(r).then(e=>{if(e.hits.length===0){a.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"yellow",position:"topRight"});return}y(),h(e.hits)}).catch(e=>{console.log(e),a.error({message:"Something went wrong :(",position:"topRight"})}).finally(()=>{S()})});
//# sourceMappingURL=index.js.map
