import{a as m,S as f,i as a}from"./assets/vendor-CBqwhNxR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const d="https://pixabay.com/api/",g="49829256-73c1564e94f64863eabbb2525";function y(o){const r={key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return m.get(d,{params:r}).then(e=>e.data).catch(e=>{throw console.log(e),e})}const h=new f(".gallery a"),u=document.querySelector(".gallery");function l(){u.innerHTML=""}function w(o){const r=o.map(e=>`<li class="g-item">
        <a href="${e.largeImageURL}"><img class="g-img" src="${e.webformatURL}" alt="${e.tags}"></a>
        <ul class="g-list">
        <li class="g-list-item"><span class="text">Likes</span> <span class="num">${e.likes}</span></li>
        <li class="g-list-item"><span class="text">Views</span> <span class="num">${e.views}</span></li>
        <li class="g-list-item"><span class="text">Comments</span> <span class="num">${e.comments}</span></li>
        <li class="g-list-item"><span class="text">Downloads</span> <span class="num">${e.downloads}</span></li>
        </ul>
        </li>`).join("");u.insertAdjacentHTML("beforeend",r),h.refresh()}const L=document.querySelector(".form"),b=document.querySelector("input"),p=document.querySelector(".loader");function S(){p.style.display="flex"}function c(){p.style.display="none"}L.addEventListener("submit",o=>{o.preventDefault(),S();const r=b.value.trim();if(!r){a.warning({message:"Please, enter a search query",color:"yellow",position:"topRight"}),c(),l();return}y(r).then(e=>{if(e.hits.length===0){a.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"yellow",position:"topRight"});return}l(),w(e.hits)}).catch(e=>{console.log(e),a.error({message:"Something went wrong :(",position:"topRight"})}).finally(()=>{c()})});
//# sourceMappingURL=index.js.map
